### ISSUE TITLE
HW2 Code Problems

### ISSUE THREAD

**Issue by gerhardpilcher** [emullan/Mullan_python#2]
I'm not able to grade HW2 yet. The functions should return something instead of printing to the screen (except for Fib). Also, you are running Python 2 instead of Python 3 as required in HW1. I included test cases at the end of your file and will commit those to the repository so your can use them to test your functions. Fix the file I've committed and make sure it passes my test cases. 

You also need to add documentation using header strings.

I will give you 90% credit if you get these fixes completed before next class.

**Comment by emullan** [comment]
Thank you for the extension. I struggled with homework #1. I thought
ipython notebook was the command window that pops up through anaconda, so i
couldn't figure out how to compile and test my code until the 2nd class,
after I had turned in the homework.

I am running python 3 on my computer. I think some of the syntax might be
python 2. I'll fix it to make sure it works on python 3 on my computer.

What do you mean by header strings? Do you mean something like '#1:
Fibonacci function to find all fibonacci numbers under a number n' at the
beginning of each function?

Thank you for the extension. I'm new to programming and am slowly learning
all the details. I'll make sure my functions pass your test cases.

Evans Mullan

**Comment by emullan** [comment]
I've fixed my code. I included comment headers for all of the functions and
my functions work for the test cases. Thank you for giving me a chance to
correct my homework. I hope homework #3 comes out better because I tested
them before turning them in. I do need to add headers to my functions in
homework 3. Can I do that now or is it too late?

**Comment by gerhardpilcher** [comment]
Not too late! Please add the headers (using doc strings so they will work with the help() function).

**Comment by gerhardpilcher** [comment]
Here's an example doc string (from class 1)

Here's an example docstring to document a function:

def total(initial=5, _numbers, *_keywords):
    """

```
This functions provides a total of all parameters sent to the function.

Parameters:
Expects numerical values.
initial - initial value defaults to 5
*numbers - any number of numbers separated by commas
**keywords - any number of name=number pairs e.g. fruit=77

"""
count = initial
for number in numbers:
    count += number #numbers stored in a tuple
for key in keywords:
    count += keywords[key] #keywords stored in a dictionary
return count
```

# For the docstring to work with help, first run the module or code segment.

# Do not include .**doc** when calling help.

help(total) 

# To print the docstring directly (not using help)

print(total.**doc**)

**Comment by gerhardpilcher** [comment]
Posted your grade.
